import type { SessionInfo } from "@robotscope/core";

import type { IncidentExplanation } from "./explain.js";
import type { IncidentRange } from "./model.js";

function seconds(ns: number): string {
  return `${(ns / 1e9).toFixed(2)}s`;
}

export function incidentReportMarkdown(
  incident: IncidentRange,
  explanation: IncidentExplanation,
  session: SessionInfo,
): string {
  const lines = [
    `# RobotScope Incident Report`,
    "",
    `- **Incident:** ${incident.label}`,
    `- **Stack:** ${incident.stack}`,
    `- **Time:** ${seconds(incident.start_ns - session.start_ns)}–${seconds(incident.end_ns - session.start_ns)} (elapsed)`,
    `- **Recording source:** ${session.source}`,
    "",
    "## Facts (observed)",
    "",
  ];

  if (explanation.facts.length === 0) {
    lines.push("- No structured evidence was available at this sample.");
  } else {
    for (const evidence of explanation.facts) {
      const threshold = evidence.threshold ? `; rule: ${evidence.threshold}` : "";
      const source = evidence.source ? `; source: \`${evidence.source}\`` : "";
      lines.push(`- **${evidence.label}:** ${evidence.observed}${threshold}${source}`);
      lines.push(`  - Entity: \`${evidence.entity_path}\``);
    }
  }

  lines.push(
    "",
    "## Inference (heuristic)",
    "",
    `> ${explanation.inference}`,
    "",
    "This inference is generated by a deterministic failure recipe. It is a debugging lead, not a proven root cause.",
    "",
    "## Correlate next",
    "",
    ...(explanation.highlight_panels.length > 0
      ? explanation.highlight_panels.map((panel) => `- \`${panel}\``)
      : ["- Review the linked entity paths around the incident time."]),
    "",
    "---",
    "Generated locally by RobotScope. Raw robot data is not embedded in this report.",
  );

  return lines.join("\n");
}
